services:
  call-center-service:
    image: call-center-service
    container_name: call-center-service
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "nginx.auth=true"
    volumes:
      - ./instance:/app/instance
    env_file:
      - .env
    networks:
      - service_network
      - public_network

networks:
  service_network:
    external: true
    name: service_network
  public_network:
    external: true
    name: public_network